[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
dynamic_padding = false
opacity = 0.9

startup_mode = "Fullscreen"

[font]
# size = 12.0
size = 11.0
# offset.y = 2

[font.normal]
# ШРИФТЫ, КОТОРЫЕ НАИБОЛЕЕ ПОНРАВИЛИСЬ
# family = "JetBrainsMonoNerdFontMono"
family = "BlexMonoNerdFontMono"
# family = "SpaceMonoNerdFontMono"

# ШРИФТЫ, КОТОРЫЕ ПОНРАВИЛИСЬ МЕНЬШЕ
# family = "GeistMonoNerdFontMono"
# family = "RecMonoLinearNerdFontMono"
# family = "SauceCodeProNerdFontMono"
# family = "VictorMonoNerdFontMono"

# Colorscheme - Zenbones Forestbones Dark Stark
[colors.bright]
black = "#45525C"
red = "#ED9294"
green = "#B0CE7B"
yellow = "#EDC77A"
blue = "#7AC9C0"
magenta = "#E5A7C4"
cyan = "#7DD093"
white = "#B2A790"
[colors.cursor]
cursor = "#CD5C5C"
#cursor = "#EBE2CF"
text = "#2C343A"
[colors.normal]
black = "#2C343A"
blue = "#7FBCB4"
cyan = "#83C193"
green = "#A9C181"
magenta = "#D69AB7"
red = "#E67C7F"
white = "#E7DCC4"
yellow = "#DDBD7F"
[colors.primary]
background = "#2C343A"
foreground = "#E7DCC4"

